# Generated by Django 5.1 on 2024-09-05 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Foto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto_url", models.URLField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "visibilidad",
                    models.CharField(
                        choices=[("public", "Publico"), ("private", "Privado")],
                        default="public",
                        max_length=7,
                    ),
                ),
                ("creacion", models.DateTimeField(auto_now_add=True)),
                ("modificacion", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Download",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descargado", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "foto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="foto.foto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_comentado", models.TextField()),
                ("creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "foto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="foto.foto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FotoMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camara", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "camara_modelo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("lente", models.CharField(blank=True, max_length=100, null=True)),
                ("apertura", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "velocidad_disparo",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("iso", models.IntegerField(blank=True, null=True)),
                (
                    "distancia_focal",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("capturada", models.DateTimeField(blank=True, null=True)),
                (
                    "foto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="foto.foto",
                    ),
                ),
            ],
        ),
    ]
