# Generated by Django 5.1 on 2024-09-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="foto",
            name="titulo",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
